### ISSUE TITLE
On ArchLinux VboxManage command is VBoxManage (With capital B)

### ISSUE THREAD

**Issue by jespino** [websecurify/node-vboxmanage#2]
This is a problem on command.coffee on vboxmanage_path initialization.

**Comment by klarkc** [comment]
+1 https://github.com/websecurify/node-vortex/issues/9

**Comment by shingonoide** [comment]
We can do symbolic link as workaround.

```
sudo ln -s /usr/bin/VBoxManage /usr/local/bin/VboxManage
```
